version: '3.8'

services:
  app:
    build: .
    container_name: react-vite-nginx
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
